###
GET https://localhost:8443/utenti/
###
GET https://localhost:8443/utenti/1
###
GET https://localhost:8443/utenti/login/paola_guarasci/ppppp
###
GET https://localhost:8443/prodotti/

###
GET https://localhost:8443/path2/prova
###
POST https://localhost:8443/path2/prova?new=angelo
###
POST https://localhost:8443/path2/prova?new=invalidate

###
GET https://localhost:8443/prova/sessionscoped/
###
POST https://localhost:8443/prova/sessionscoped


giovanni

###
GET https://localhost:8443/requestscoped/
###
POST https://localhost:8443/requestscoped/post

giorgia

###
GET https://localhost:8443/applicationscoped/
###
POST https://localhost:8443/applicationscoped/post

angelo

###
POST https://localhost:8443/utenti/auth/login

giobiam, 12345

###
GET https://localhost:8443/utenti/1
###
GET https://localhost:8443/prodotti

###
POST https://localhost:8443/utenti/auth/registrazione
Content-Type: application/json

{"username": "prova", "password": "prova", "nome": "prova", "cognome": "prova", "indirizzo": "prova", "ruolo": "USER"}

###
POST https://localhost:8443/utenti/auth/login
Content-Type: application/json

{"username": "adminglf", "password": "adminglf"}

###

@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODUxMTc4NjMsImlhdCI6MTY4NTExMDY2MywidXNlcm5hbWUiOiJhZG1pbmdsZiJ9.2W0hlvUM_XSQqI_OECSQJdaGFEGEARDfHJKUMXIYn4s
###
GET https://localhost:8443/admin/userlist
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODUxODI1MDAsImlhdCI6MTY4NTE3NTMwMCwidXNlcm5hbWUiOiJhZG1pbmdsZiJ9.0zkeuHq__Ld5Fo1EQrUzwUgjrSQnNGFfG8zajLSwlYY

###
GET https://localhost:8443/admin/acquistilist
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODUxODI1MDAsImlhdCI6MTY4NTE3NTMwMCwidXNlcm5hbWUiOiJhZG1pbmdsZiJ9.0zkeuHq__Ld5Fo1EQrUzwUgjrSQnNGFfG8zajLSwlYY