spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/GlutenFreeShop
        password: 15giu
        username: postgres
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false

server:
    ssl:
        key-store-type: PKCS12
        key-store: classpath:paola_certificato.p12
        key-store-password: paola2023
        key-alias: paola
        enabled: true